// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAccount = `-- name: GetAccount :one
SELECT id, currency, balance, held_amount, floor, allow_negative, version, external_ref, created_at, updated_at FROM accounts WHERE id = $1
`

func (q *Queries) GetAccount(ctx context.Context, id string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Currency,
		&i.Balance,
		&i.HeldAmount,
		&i.Floor,
		&i.AllowNegative,
		&i.Version,
		&i.ExternalRef,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByExternalRef = `-- name: GetAccountByExternalRef :one
SELECT id, currency, balance, held_amount, floor, allow_negative, version, external_ref, created_at, updated_at FROM accounts WHERE external_ref = $1
`

func (q *Queries) GetAccountByExternalRef(ctx context.Context, externalRef pgtype.Text) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByExternalRef, externalRef)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Currency,
		&i.Balance,
		&i.HeldAmount,
		&i.Floor,
		&i.AllowNegative,
		&i.Version,
		&i.ExternalRef,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountForUpdate = `-- name: GetAccountForUpdate :one
SELECT id, currency, balance, held_amount, floor, allow_negative, version, external_ref, created_at, updated_at FROM accounts WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetAccountForUpdate(ctx context.Context, id string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountForUpdate, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Currency,
		&i.Balance,
		&i.HeldAmount,
		&i.Floor,
		&i.AllowNegative,
		&i.Version,
		&i.ExternalRef,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAccount = `-- name: InsertAccount :one
INSERT INTO accounts (id, currency, balance, held_amount, floor, allow_negative, version, external_ref)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, currency, balance, held_amount, floor, allow_negative, version, external_ref, created_at, updated_at
`

type InsertAccountParams struct {
	ID            string      `json:"id"`
	Currency      string      `json:"currency"`
	Balance       int64       `json:"balance"`
	HeldAmount    int64       `json:"held_amount"`
	Floor         int64       `json:"floor"`
	AllowNegative bool        `json:"allow_negative"`
	Version       int64       `json:"version"`
	ExternalRef   pgtype.Text `json:"external_ref"`
}

func (q *Queries) InsertAccount(ctx context.Context, arg InsertAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, insertAccount,
		arg.ID,
		arg.Currency,
		arg.Balance,
		arg.HeldAmount,
		arg.Floor,
		arg.AllowNegative,
		arg.Version,
		arg.ExternalRef,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Currency,
		&i.Balance,
		&i.HeldAmount,
		&i.Floor,
		&i.AllowNegative,
		&i.Version,
		&i.ExternalRef,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAccountBalance = `-- name: UpdateAccountBalance :one
UPDATE accounts
SET
    balance     = $2,
    held_amount = $3,
    version     = version + 1,
    updated_at  = NOW()
WHERE id = $1 AND version = $4
RETURNING id, currency, balance, held_amount, floor, allow_negative, version, external_ref, created_at, updated_at
`

type UpdateAccountBalanceParams struct {
	ID         string `json:"id"`
	Balance    int64  `json:"balance"`
	HeldAmount int64  `json:"held_amount"`
	Version    int64  `json:"version"`
}

// Optimistic lock via version check; returns updated row or no rows if version mismatch.
func (q *Queries) UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccountBalance,
		arg.ID,
		arg.Balance,
		arg.HeldAmount,
		arg.Version,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Currency,
		&i.Balance,
		&i.HeldAmount,
		&i.Floor,
		&i.AllowNegative,
		&i.Version,
		&i.ExternalRef,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
