// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: holds.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getActiveHoldsByAccountID = `-- name: GetActiveHoldsByAccountID :many
SELECT id, account_id, amount, currency, status, expires_at, external_ref, created_at, updated_at FROM holds WHERE account_id = $1 AND status = 'active' ORDER BY created_at
`

func (q *Queries) GetActiveHoldsByAccountID(ctx context.Context, accountID string) ([]Hold, error) {
	rows, err := q.db.Query(ctx, getActiveHoldsByAccountID, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Hold
	for rows.Next() {
		var i Hold
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.ExpiresAt,
			&i.ExternalRef,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExpiredHolds = `-- name: GetExpiredHolds :many
SELECT id, account_id, amount, currency, status, expires_at, external_ref, created_at, updated_at FROM holds
WHERE status = 'active' AND expires_at <= NOW()
ORDER BY expires_at
LIMIT $1
`

// Hold expiry worker: fetch expired active holds for processing.
func (q *Queries) GetExpiredHolds(ctx context.Context, limit int32) ([]Hold, error) {
	rows, err := q.db.Query(ctx, getExpiredHolds, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Hold
	for rows.Next() {
		var i Hold
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.ExpiresAt,
			&i.ExternalRef,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHoldForUpdate = `-- name: GetHoldForUpdate :one
SELECT id, account_id, amount, currency, status, expires_at, external_ref, created_at, updated_at FROM holds WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetHoldForUpdate(ctx context.Context, id string) (Hold, error) {
	row := q.db.QueryRow(ctx, getHoldForUpdate, id)
	var i Hold
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.ExpiresAt,
		&i.ExternalRef,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertHold = `-- name: InsertHold :one
INSERT INTO holds (id, account_id, amount, currency, expires_at, external_ref)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, account_id, amount, currency, status, expires_at, external_ref, created_at, updated_at
`

type InsertHoldParams struct {
	ID          string             `json:"id"`
	AccountID   string             `json:"account_id"`
	Amount      int64              `json:"amount"`
	Currency    string             `json:"currency"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	ExternalRef pgtype.Text        `json:"external_ref"`
}

func (q *Queries) InsertHold(ctx context.Context, arg InsertHoldParams) (Hold, error) {
	row := q.db.QueryRow(ctx, insertHold,
		arg.ID,
		arg.AccountID,
		arg.Amount,
		arg.Currency,
		arg.ExpiresAt,
		arg.ExternalRef,
	)
	var i Hold
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.ExpiresAt,
		&i.ExternalRef,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateHoldStatus = `-- name: UpdateHoldStatus :one
UPDATE holds
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, account_id, amount, currency, status, expires_at, external_ref, created_at, updated_at
`

type UpdateHoldStatusParams struct {
	ID     string     `json:"id"`
	Status HoldStatus `json:"status"`
}

func (q *Queries) UpdateHoldStatus(ctx context.Context, arg UpdateHoldStatusParams) (Hold, error) {
	row := q.db.QueryRow(ctx, updateHoldStatus, arg.ID, arg.Status)
	var i Hold
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.ExpiresAt,
		&i.ExternalRef,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
