// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: journal_entries.sql

package store

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const getJournalEntry = `-- name: GetJournalEntry :one
SELECT id, idempotency_key, business_date, value_date, booked_at, reverses_id, external_ref, metadata, created_at FROM journal_entries WHERE id = $1
`

func (q *Queries) GetJournalEntry(ctx context.Context, id string) (JournalEntry, error) {
	row := q.db.QueryRow(ctx, getJournalEntry, id)
	var i JournalEntry
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.BusinessDate,
		&i.ValueDate,
		&i.BookedAt,
		&i.ReversesID,
		&i.ExternalRef,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getJournalEntryByIdempotencyKey = `-- name: GetJournalEntryByIdempotencyKey :one
SELECT id, idempotency_key, business_date, value_date, booked_at, reverses_id, external_ref, metadata, created_at FROM journal_entries WHERE idempotency_key = $1
`

func (q *Queries) GetJournalEntryByIdempotencyKey(ctx context.Context, idempotencyKey string) (JournalEntry, error) {
	row := q.db.QueryRow(ctx, getJournalEntryByIdempotencyKey, idempotencyKey)
	var i JournalEntry
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.BusinessDate,
		&i.ValueDate,
		&i.BookedAt,
		&i.ReversesID,
		&i.ExternalRef,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const insertJournalEntry = `-- name: InsertJournalEntry :one
INSERT INTO journal_entries (id, idempotency_key, business_date, value_date, booked_at, reverses_id, external_ref, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, idempotency_key, business_date, value_date, booked_at, reverses_id, external_ref, metadata, created_at
`

type InsertJournalEntryParams struct {
	ID             string             `json:"id"`
	IdempotencyKey string             `json:"idempotency_key"`
	BusinessDate   pgtype.Date        `json:"business_date"`
	ValueDate      pgtype.Date        `json:"value_date"`
	BookedAt       pgtype.Timestamptz `json:"booked_at"`
	ReversesID     pgtype.Text        `json:"reverses_id"`
	ExternalRef    pgtype.Text        `json:"external_ref"`
	Metadata       json.RawMessage    `json:"metadata"`
}

func (q *Queries) InsertJournalEntry(ctx context.Context, arg InsertJournalEntryParams) (JournalEntry, error) {
	row := q.db.QueryRow(ctx, insertJournalEntry,
		arg.ID,
		arg.IdempotencyKey,
		arg.BusinessDate,
		arg.ValueDate,
		arg.BookedAt,
		arg.ReversesID,
		arg.ExternalRef,
		arg.Metadata,
	)
	var i JournalEntry
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.BusinessDate,
		&i.ValueDate,
		&i.BookedAt,
		&i.ReversesID,
		&i.ExternalRef,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}
