// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type HoldStatus string

const (
	HoldStatusActive   HoldStatus = "active"
	HoldStatusCaptured HoldStatus = "captured"
	HoldStatusVoided   HoldStatus = "voided"
	HoldStatusExpired  HoldStatus = "expired"
)

func (e *HoldStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = HoldStatus(s)
	case string:
		*e = HoldStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for HoldStatus: %T", src)
	}
	return nil
}

type NullHoldStatus struct {
	HoldStatus HoldStatus `json:"hold_status"`
	Valid      bool       `json:"valid"` // Valid is true if HoldStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullHoldStatus) Scan(value interface{}) error {
	if value == nil {
		ns.HoldStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.HoldStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullHoldStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.HoldStatus), nil
}

type PostingDirection string

const (
	PostingDirectionDEBIT  PostingDirection = "DEBIT"
	PostingDirectionCREDIT PostingDirection = "CREDIT"
)

func (e *PostingDirection) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PostingDirection(s)
	case string:
		*e = PostingDirection(s)
	default:
		return fmt.Errorf("unsupported scan type for PostingDirection: %T", src)
	}
	return nil
}

type NullPostingDirection struct {
	PostingDirection PostingDirection `json:"posting_direction"`
	Valid            bool             `json:"valid"` // Valid is true if PostingDirection is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPostingDirection) Scan(value interface{}) error {
	if value == nil {
		ns.PostingDirection, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PostingDirection.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPostingDirection) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PostingDirection), nil
}

type Account struct {
	ID            pgtype.UUID        `json:"id"`
	Currency      string             `json:"currency"`
	Balance       int64              `json:"balance"`
	HeldAmount    int64              `json:"held_amount"`
	Floor         int64              `json:"floor"`
	AllowNegative bool               `json:"allow_negative"`
	Version       int64              `json:"version"`
	ExternalRef   pgtype.Text        `json:"external_ref"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Hold struct {
	ID          pgtype.UUID        `json:"id"`
	AccountID   pgtype.UUID        `json:"account_id"`
	Amount      int64              `json:"amount"`
	Currency    string             `json:"currency"`
	Status      HoldStatus         `json:"status"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	ExternalRef pgtype.Text        `json:"external_ref"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type JournalEntry struct {
	ID             pgtype.UUID        `json:"id"`
	IdempotencyKey string             `json:"idempotency_key"`
	BusinessDate   pgtype.Date        `json:"business_date"`
	ValueDate      pgtype.Date        `json:"value_date"`
	BookedAt       pgtype.Timestamptz `json:"booked_at"`
	ReversesID     pgtype.UUID        `json:"reverses_id"`
	ExternalRef    pgtype.Text        `json:"external_ref"`
	Metadata       json.RawMessage    `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type OutboxEvent struct {
	ID            pgtype.UUID        `json:"id"`
	AggregateType string             `json:"aggregate_type"`
	AggregateID   string             `json:"aggregate_id"`
	EventType     string             `json:"event_type"`
	Payload       json.RawMessage    `json:"payload"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Posting struct {
	ID        pgtype.UUID        `json:"id"`
	EntryID   pgtype.UUID        `json:"entry_id"`
	AccountID pgtype.UUID        `json:"account_id"`
	Amount    int64              `json:"amount"`
	Direction PostingDirection   `json:"direction"`
	Currency  string             `json:"currency"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
