// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: postings.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPostingsByAccountID = `-- name: GetPostingsByAccountID :many
SELECT id, entry_id, account_id, amount, direction, currency, created_at FROM postings WHERE account_id = $1 ORDER BY created_at
`

func (q *Queries) GetPostingsByAccountID(ctx context.Context, accountID pgtype.UUID) ([]Posting, error) {
	rows, err := q.db.Query(ctx, getPostingsByAccountID, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Posting
	for rows.Next() {
		var i Posting
		if err := rows.Scan(
			&i.ID,
			&i.EntryID,
			&i.AccountID,
			&i.Amount,
			&i.Direction,
			&i.Currency,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostingsByEntryID = `-- name: GetPostingsByEntryID :many
SELECT id, entry_id, account_id, amount, direction, currency, created_at FROM postings WHERE entry_id = $1 ORDER BY created_at
`

func (q *Queries) GetPostingsByEntryID(ctx context.Context, entryID pgtype.UUID) ([]Posting, error) {
	rows, err := q.db.Query(ctx, getPostingsByEntryID, entryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Posting
	for rows.Next() {
		var i Posting
		if err := rows.Scan(
			&i.ID,
			&i.EntryID,
			&i.AccountID,
			&i.Amount,
			&i.Direction,
			&i.Currency,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPosting = `-- name: InsertPosting :one
INSERT INTO postings (id, entry_id, account_id, amount, direction, currency)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, entry_id, account_id, amount, direction, currency, created_at
`

type InsertPostingParams struct {
	ID        pgtype.UUID      `json:"id"`
	EntryID   pgtype.UUID      `json:"entry_id"`
	AccountID pgtype.UUID      `json:"account_id"`
	Amount    int64            `json:"amount"`
	Direction PostingDirection `json:"direction"`
	Currency  string           `json:"currency"`
}

func (q *Queries) InsertPosting(ctx context.Context, arg InsertPostingParams) (Posting, error) {
	row := q.db.QueryRow(ctx, insertPosting,
		arg.ID,
		arg.EntryID,
		arg.AccountID,
		arg.Amount,
		arg.Direction,
		arg.Currency,
	)
	var i Posting
	err := row.Scan(
		&i.ID,
		&i.EntryID,
		&i.AccountID,
		&i.Amount,
		&i.Direction,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}
