// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	GetAccount(ctx context.Context, id pgtype.UUID) (Account, error)
	GetAccountByExternalRef(ctx context.Context, externalRef pgtype.Text) (Account, error)
	GetAccountForUpdate(ctx context.Context, id pgtype.UUID) (Account, error)
	GetActiveHoldsByAccountID(ctx context.Context, accountID pgtype.UUID) ([]Hold, error)
	// Verification job: returns accounts whose stored balance diverges from the
	// sum of their postings. Any row here is a ledger invariant violation.
	GetBalanceMismatches(ctx context.Context) ([]GetBalanceMismatchesRow, error)
	// Hold expiry worker: fetch expired active holds for processing.
	GetExpiredHolds(ctx context.Context, limit int32) ([]Hold, error)
	GetHold(ctx context.Context, id pgtype.UUID) (Hold, error)
	GetHoldForUpdate(ctx context.Context, id pgtype.UUID) (Hold, error)
	GetJournalEntry(ctx context.Context, id pgtype.UUID) (JournalEntry, error)
	GetJournalEntryByIdempotencyKey(ctx context.Context, idempotencyKey string) (JournalEntry, error)
	GetPostingsByAccountID(ctx context.Context, accountID pgtype.UUID) ([]Posting, error)
	GetPostingsByEntryID(ctx context.Context, entryID pgtype.UUID) ([]Posting, error)
	// Relay worker: fetch next batch of unpublished events in insertion order.
	GetUnpublishedOutboxEvents(ctx context.Context, limit int32) ([]OutboxEvent, error)
	InsertAccount(ctx context.Context, arg InsertAccountParams) (Account, error)
	InsertHold(ctx context.Context, arg InsertHoldParams) (Hold, error)
	InsertJournalEntry(ctx context.Context, arg InsertJournalEntryParams) (JournalEntry, error)
	InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) (OutboxEvent, error)
	InsertPosting(ctx context.Context, arg InsertPostingParams) (Posting, error)
	MarkOutboxEventPublished(ctx context.Context, id pgtype.UUID) (OutboxEvent, error)
	// Optimistic lock via version check; returns updated row or no rows if version mismatch.
	UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) (Account, error)
	UpdateHoldStatus(ctx context.Context, arg UpdateHoldStatusParams) (Hold, error)
}

var _ Querier = (*Queries)(nil)
