// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: verification.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getBalanceMismatches = `-- name: GetBalanceMismatches :many
SELECT
    a.id,
    a.currency,
    a.balance                                                         AS stored_balance,
    COALESCE(SUM(
        CASE WHEN p.direction = 'DEBIT' THEN -p.amount
             ELSE p.amount END
    ), 0)::bigint                                                     AS computed_balance
FROM accounts a
LEFT JOIN postings p ON p.account_id = a.id
GROUP BY a.id, a.currency, a.balance
HAVING a.balance <> COALESCE(SUM(
    CASE WHEN p.direction = 'DEBIT' THEN -p.amount
         ELSE p.amount END
), 0)
`

type GetBalanceMismatchesRow struct {
	ID              pgtype.UUID `json:"id"`
	Currency        string      `json:"currency"`
	StoredBalance   int64       `json:"stored_balance"`
	ComputedBalance int64       `json:"computed_balance"`
}

// Verification job: returns accounts whose stored balance diverges from the
// sum of their postings. Any row here is a ledger invariant violation.
func (q *Queries) GetBalanceMismatches(ctx context.Context) ([]GetBalanceMismatchesRow, error) {
	rows, err := q.db.Query(ctx, getBalanceMismatches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBalanceMismatchesRow
	for rows.Next() {
		var i GetBalanceMismatchesRow
		if err := rows.Scan(
			&i.ID,
			&i.Currency,
			&i.StoredBalance,
			&i.ComputedBalance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
