// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject

package app

import (
	"github.com/go-chi/chi/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

// InitializeApp wires up the application. Placeholder until real routes are added.
func InitializeApp(r *chi.Mux, pool *pgxpool.Pool) error {
	return nil
}
